// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXwVi_QkTfMCXCcVlrem8lYP_fbvICgGI',
    appId: '1:458842867125:android:91e109fdc7c28ee96485fc',
    messagingSenderId: '458842867125',
    projectId: 'trialtest-b6813',
    databaseURL: 'https://trialtest-b6813-default-rtdb.firebaseio.com',
    storageBucket: 'trialtest-b6813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuW013IzNdWKrIrZaStODZQ9hz3CgOYwY',
    appId: '1:458842867125:ios:28a67ed6667ed6ec6485fc',
    messagingSenderId: '458842867125',
    projectId: 'trialtest-b6813',
    databaseURL: 'https://trialtest-b6813-default-rtdb.firebaseio.com',
    storageBucket: 'trialtest-b6813.firebasestorage.app',
    androidClientId: '458842867125-jrgo0bcgma2tqo3e39aue5bgcpah5mge.apps.googleusercontent.com',
    iosClientId: '458842867125-6d51aquf85cn6n4kq5s32ti6741d7qst.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApplication',
  );
}
